/**
 * RBAC Decorators — Permission-based
 * Generated by ddd-codegen
 * @RequirePermissions decorator for NestJS controllers
 */

import { SetMetadata } from '@nestjs/common';
import { Permission } from '../rbac/permissions.enum';

export const PERMISSIONS_KEY = 'rbac:permissions';
export const RequirePermissions = (...permissions: Permission[]) =>
  SetMetadata(PERMISSIONS_KEY, permissions);
