@startuml CourseManagementActivity

|RegisterStudentUseCase|
start

:open;
:newObject(Student);
:setDataFieldValues(name,email);
:createObject(Student);

|EnrollStudentUseCase|
:open;
:newObject(Enrolment);
:setDataFieldValues(studentId,courseModuleId);
:createObject(Enrolment);

|Student|
if (helpRequested?) then (yes)
    :requestHelp;
endif

stop
@enduml